/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Wed Feb 11 16:53:02 2015. */

#include "seige.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t seige_request_t_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, seige_request_t, session_id, session_id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, seige_request_t, requester, session_id, 0),
    PB_LAST_FIELD
};

const pb_field_t seige_response_t_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, seige_response_t, session_id, session_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, seige_response_t, b_allow, session_id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, seige_response_t, current_requester, b_allow, 0),
    PB_LAST_FIELD
};


