/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Wed Feb 11 16:53:02 2015. */

#ifndef PB_SEIGE_PB_H_INCLUDED
#define PB_SEIGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _seige_request_t {
    char session_id[20];
    char requester[20];
} seige_request_t;

typedef struct _seige_response_t {
    char session_id[20];
    int32_t b_allow;
    bool has_current_requester;
    char current_requester[20];
} seige_response_t;

/* Default values for struct fields */

/* Initializer values for message structs */
#define seige_request_t_init_default             {"", ""}
#define seige_response_t_init_default            {"", 0, false, ""}
#define seige_request_t_init_zero                {"", ""}
#define seige_response_t_init_zero               {"", 0, false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define seige_request_t_session_id_tag           1
#define seige_request_t_requester_tag            2
#define seige_response_t_session_id_tag          1
#define seige_response_t_b_allow_tag             2
#define seige_response_t_current_requester_tag   3

/* Struct field encoding specification for nanopb */
extern const pb_field_t seige_request_t_fields[3];
extern const pb_field_t seige_response_t_fields[4];

/* Maximum encoded size of messages (where known) */
#define seige_request_t_size                     44
#define seige_response_t_size                    55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
