/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Tue Jan 20 23:14:59 2015. */

#ifndef PB_PTT_SESSION_PB_H_INCLUDED
#define PB_PTT_SESSION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _PTTSession {
    char ipaddr[40];
    int32_t port;
} PTTSession;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PTTSession_init_default                  {"", 0}
#define PTTSession_init_zero                     {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define PTTSession_ipaddr_tag                    1
#define PTTSession_port_tag                      2

/* Struct field encoding specification for nanopb */
extern const pb_field_t PTTSession_fields[3];

/* Maximum encoded size of messages (where known) */
#define PTTSession_size                          53

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
