/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Jan 20 23:14:59 2015. */

#include "ptt-session.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PTTSession_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, PTTSession, ipaddr, ipaddr, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, PTTSession, port, ipaddr, 0),
    PB_LAST_FIELD
};


